/**
 * Centralized machine-readable error codes.
 *
 * Every error thrown in the system MUST use one of these codes
 * to ensure consistent client-side error handling.
 */
const ErrorCodes = Object.freeze({
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  FORBIDDEN: 'FORBIDDEN',
  TENANT_CONTEXT_REQUIRED: 'TENANT_CONTEXT_REQUIRED',

  // Bookings
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_NOT_AVAILABLE: 'TRIP_NOT_AVAILABLE',
  NOT_ENOUGH_SEATS: 'NOT_ENOUGH_SEATS',
  SEAT_ALREADY_BOOKED: 'SEAT_ALREADY_BOOKED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CANNOT_CANCEL: 'BOOKING_CANNOT_CANCEL',
  BOOKING_CONCURRENT: 'BOOKING_CONCURRENT',

  // Payments
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_INVALID_TRANSITION: 'PAYMENT_INVALID_TRANSITION',
  BOOKING_ALREADY_PAID: 'BOOKING_ALREADY_PAID',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  DUPLICATE_WEBHOOK: 'DUPLICATE_WEBHOOK',
  WEBHOOK_VALIDATION_FAILED: 'WEBHOOK_VALIDATION_FAILED',

  // Trips
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  BUS_NOT_FOUND: 'BUS_NOT_FOUND',
  TRIP_ALREADY_ACTIVE: 'TRIP_ALREADY_ACTIVE',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  CANNOT_SELF_LOCK: 'CANNOT_SELF_LOCK',
  CANNOT_SELF_DELETE: 'CANNOT_SELF_DELETE',

  // Tickets
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_USED: 'TICKET_ALREADY_USED',
  TICKET_ALREADY_EXISTS: 'TICKET_ALREADY_EXISTS',

  // Stations
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  STATION_ALREADY_EXISTS: 'STATION_ALREADY_EXISTS',
  ROUTE_ALREADY_EXISTS: 'ROUTE_ALREADY_EXISTS',
  TRIP_ALREADY_EXISTS: 'TRIP_ALREADY_EXISTS',

  // Tenants
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_EXISTS: 'TENANT_EXISTS',

  // Refunds
  REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
  REFUND_ALREADY_PROCESSED: 'REFUND_ALREADY_PROCESSED',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // GPS
  GPS_UNAUTHORIZED_ROLE: 'GPS_UNAUTHORIZED_ROLE',
  GPS_TRIP_NOT_ACTIVE: 'GPS_TRIP_NOT_ACTIVE',
  GPS_BUS_MISMATCH: 'GPS_BUS_MISMATCH',
  GPS_MISSING_FIELDS: 'GPS_MISSING_FIELDS',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = ErrorCodes;
