module.exports = {
  testEnvironment: 'node',
  testTimeout: 30000,
  roots: ['<rootDir>'],
  modulePaths: ['<rootDir>/../backend/node_modules'],
  moduleDirectories: ['node_modules', '<rootDir>/../backend/node_modules'],
  setupFilesAfterEnv: ['<rootDir>/setup/setup.js'],
  globalTeardown: '<rootDir>/setup/teardown.js',
  collectCoverage: false,
  testMatch: [
    '**/tests/auth/**/*.test.js',
    '**/tests/stations/**/*.test.js',
    '**/tests/buses/**/*.test.js',
    '**/tests/routes/**/*.test.js',
    '**/tests/trips/**/*.test.js',
    '**/tests/bookings/**/*.test.js',
    '**/tests/payments/**/*.test.js',
    '**/tests/tickets/**/*.test.js',
    '**/tests/tracking/**/*.test.js',
    '**/tests/tenants/**/*.test.js',
    '**/tests/backoffice/**/*.test.js',
    '**/tests/mobile/**/*.test.js',
    '**/tests/superadmin/**/*.test.js',
    '**/tests/redis/**/*.test.js',
    '**/tests/rabbitmq/**/*.test.js',
    '**/tests/e2e/**/*.test.js',
  ],
  testPathIgnorePatterns: ['/node_modules/'],
  modulePathIgnorePatterns: ['<rootDir>/../backend/node_modules'],
};
